In [23]:
import pandas as pd

# Load TRMM
trmm = pd.read_csv("C:/Users/priya/PycharmProjects/Coastal-prediction/dataset/rainfall_trmm.csv")

# Load GPM
gpm = pd.read_csv("C:/Users/priya/PycharmProjects/Coastal-prediction/dataset/rainfall_gpm.csv")

# Standardize column names
trmm.columns = ["Date", "Rainfall"]
gpm.columns = ["Date", "Rainfall"]

# Convert Date column to datetime
trmm["Date"] = pd.to_datetime(trmm["Date"])
gpm["Date"] = pd.to_datetime(gpm["Date"])

# Combine both datasets
rainfall = pd.concat([trmm, gpm])

# Sort by date
rainfall = rainfall.sort_values("Date")

# Remove duplicates if any
rainfall = rainfall.drop_duplicates()

# Remove negative rainfall
rainfall["Rainfall"] = rainfall["Rainfall"].clip(lower=0)

rainfall

           Date   Rainfall
0    1998-01-02   0.010306
1    1998-01-03   0.023861
2    1998-01-04   0.000000
3    1998-01-05   0.000000
4    1998-01-06   0.000000
...         ...        ...
3920 2025-09-26   8.059369
3921 2025-09-27   6.688069
3922 2025-09-28  16.828831
3923 2025-09-29  24.443644
3924 2025-09-30   3.980065

[11629 rows x 2 columns]

In [24]:
# Read semicolon-separated txt file
sea = pd.read_csv("C:/Users/priya/PycharmProjects/Coastal-prediction/dataset/sealevel_chennai.txt", sep=";", header=None)

In [25]:
#The sealevel data doesn't contain any columns so we have to add it manually
sea.columns = ["Decimal_Year", "Sea_Level_mm", "Flag", "Quality"]

In [26]:
sea.head()

   Decimal_Year  Sea_Level_mm  Flag  Quality
0     1916.0417          6897     0        0
1     1916.1250          6833     0        0
2     1916.2083          6806     0        0
3     1916.2917          6879     0        0
4     1916.3750          6979     0        0

In [27]:
#Sometimes numbers have spaces. Remove them.
sea["Decimal_Year"] = sea["Decimal_Year"].astype(str).str.strip()
sea["Sea_Level_mm"] = sea["Sea_Level_mm"].astype(str).str.strip()

In [28]:
#Convert the data into numeric values
sea["Decimal_Year"] = pd.to_numeric(sea["Decimal_Year"], errors="coerce")
sea["Sea_Level_mm"] = pd.to_numeric(sea["Sea_Level_mm"], errors="coerce")

In [29]:
sea["Sea_Level_mm"].unique()

array([  6897,   6833,   6806,   6879,   6979,   7046,   6992,   6937,
         7062,   7123,   7196,   7077,   6958,   6900,   6882,   6888,
         6922,   6870,   6952,   6998,   7080,   7278,   7071,   7040,
         6845,   6766,   6739,   6925,   6912,   6830,   6812,   6961,
         7028,   7235,   6918,   6787,   6790,   6781,   6982,   7031,
         6909,   6943,   7251,   7150,   7016,   6839,   6876,   6970,
         6931,   6915,   7068,   7004, -99999,   6987,   7151,   7292,
         7084,   6984,   6926,   6883,   6889,   6938,   7002,   6917,
         6911,   7030,   7145,   7020,   6920,   6929,   6841,   6831,
         6944,   7011,   7005,   7240,   7231,   7215,   7027,   6975,
         6950,   6956,   7100,   6993,   7200,   7304,   7097,   6932,
         6895,   7023,   6959,   6914,   6953,   7087,   7161,   7060,
         6853,   6902,   7033,   7048,   7118,   7057,   6927,   6838,
         6835,   6789,   6942,   6990,   6916,   6973,   7104,   7287,
         7111,   6965,   6818,   6863,   7091,   7078,   7146,   7258,
         7073,   6899,   7006,   7036,   7019,   7007,   7102,   7245,
         7122,   7021,   6903,   6951,   7013,   6936,   6862,   6898,
         6989,   7017,   6974,   6947,   7067,   7086,   6983,   7243,
         7233,   7083,   7065,   6874,   6894,   6848,   6968,   7014,
         6875,   7124,   7022,   6955,   6996,   7110,   7293,   7112,
         6939,   6921,   7069,   6994,   7050,   7147,   6866,   6801,
         6824,   7025,   7185,   7178,   7186,   6871,   6885,   7044,
         7042,   6988,   6846,   6880,   6896,   6935,   6964,   7061,
         6822,   6858,   6851,   7032,   7101,   7137,   7126,   7029,
         6971,   7166,   7316,   7051,   6976,   6957,   6877,   7009,
         6980,   7162,   7259,   6904,   6905,   6868,   6854,   6827,
         6948,   6972,   7167,   7334,   7153,   6978,   6891,   6856,
         7045,   6986,   7138,   7318,   7156,   6981,   6860,   6893,
         7179,   7212,   6844,   6807,   6864,   6849,   6966,   7114,
         7001,   6913,   6995,   6928,   6933,   7169,   7056,   6869,
         7089,   7229,   6881,   7115,   7329,   7184,   6852,   6872,
         7008,   6945,   6802,   7015,   6867,   6797,   7024,   6887,
         7369,   7175,   7052,   7165,   7280,   7047,   6977,   6855,
         7064,   6907,   6836,   6842,   7106,   7074,   7277,   7173,
         7094,   6997,   6949,   7012,   7063,   6941,   7119,   6765,
         6814,   6999,   7120,   6829,   6954,   7053,   6832,   7058,
         7143,   6985,   6906,   6940,   6890,   6840,   7035,   7183,
         7216,   7107,   7158,   7194,   7108,   7055,   6930,   7079,
         7205,   7010,   7000,   7105,   7263,   7109,   7296,   7144,
         6963,   7003,   7159,   6960,   6901,   7095,   7154,   6861,
         7049,   6857,   6769,   6969,   7018,   7255,   7192,   6991,
         6865,   6878,   6783,   6946,   7234,   7182,   7070,   6967,
         7307,   7134,   7026,   7085,   7117,   7135,   6924,   7098,
         7288,   7284,   7217,   7174,   7054,   7152,   6923,   7247,
         7041,   7203,   7127,   6934,   7193,   7082,   7187,   7039,
         7136,   7261,   7264,   7197,   7096,   7189,   7076,   7125,
         7075,   7224,   7132,   7222,   7395,   7515,   7363,   7301,
         7219,   7220,   7214,   7241,   7376,   7170,   7237,   7279,
         7248,   7265,   7314,   7498,   7447,   7142,   7253])

In [30]:
sea["Sea_Level_mm"] = sea["Sea_Level_mm"].replace(-99999, pd.NA)

In [31]:
#drop missing rows
sea = sea.dropna(subset=["Sea_Level_mm"])

In [32]:
#The data contains years in decimal in the format 1987.04175 which resembles 1987 the decimal represents Jan month
sea["Year"] = sea["Decimal_Year"].astype(int)

In [33]:
sea["Decimal_Part"] = sea["Decimal_Year"] - sea["Year"]

In [34]:
sea["Month"] = (sea["Decimal_Part"] * 12 + 1).round().astype(int)

In [35]:
sea["Date"] = pd.to_datetime(dict(year=sea["Year"], month=sea["Month"], day=1))

In [36]:
#This code simply have only the necessary columns for the analysis
sea = sea[["Date", "Sea_Level_mm"]]

In [37]:
sea.head()
sea.tail()

           Date Sea_Level_mm
1284 2023-02-01         7301
1290 2023-08-01         7142
1291 2023-08-01         7052
1292 2023-09-01         7069
1294 2023-12-01         7253

In [38]:
sea["Date"].min()
sea["Date"].max()

Timestamp('2023-12-01 00:00:00')

In [40]:
sea = sea.sort_values("Date")
sea = sea.reset_index(drop=True)
sea

          Date Sea_Level_mm
0   1916-02-01         6897
1   1916-02-01         6833
2   1916-03-01         6806
3   1916-05-01         6879
4   1916-06-01         6979
..         ...          ...
812 2023-02-01         7301
813 2023-08-01         7142
814 2023-08-01         7052
815 2023-09-01         7069
816 2023-12-01         7253

[817 rows x 2 columns]